language: python
python:
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - pip install nose coverage pep8 PyYAML catkin_pkg rospkg empy coveralls --use-mirrors
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install ros-hydro-roslaunch ros-hydro-rospy ros-hydro-std-msgs ros-hydro-std-srvs ros-hydro-geometry-msgs ros-hydro-message-generation ros-hydro-message-runtime ros-hydro-catkin
# command to run tests
script:
  - nosetests -s --tests test --with-coverage --cover-package capabilities
  - mkdir build
  - cd build
  - source /opt/ros/hydro/setup.bash
  - cmake ..
  - make
  - make run_tests
  - catkin_test_results test_results
notifications:
  email: false
matrix:
  allow_failures:
    - python: "3.2"
after_success:
  - ls
  - coveralls
